# SFE4J configuration
sfe4j:
  base-dir-path: "/"
  restrict-to-base-dir: false
  title: "SFE4J Demo"
  description: "Simple File Explorer for spring-boot based Java Web Application."
  quick-links:
    root: /
    logs: /data/logs

# Logging
logging:
  file:
    name: /data/logs/app.log
